import { Products } from './types/Products';

export const sampleProducts: Products[] = [
  {
    name: 'Nike Slim shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../images/p1.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'PUMA Slim shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../images/p2.jpg',
    price: 320,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.0,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Amavubi Slim shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../images/p3.jpg',
    price: 220,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.8,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Visit Slim shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../images/p4.jpg',
    price: 500,
    countInStock: 10,
    brand: 'Nike',
    rating: 5.0,
    numReviews: 70,
    description: 'high quality shirt',
  },
];